name: Monkey Bar

on:
  schedule:
    # Runs at 13:00 UTC (09:00 EDT when DST is active)
    - cron: '0 13 * * *'
    # Runs at 14:00 UTC (09:00 EST when standard time is active)
    - cron: '0 14 * * *'
    - cron: '5 * * * *'

jobs:
  run-binary:
      runs-on: ubuntu-latest
      env:
        RES_DAYS_AHEAD: "20"
        VENUE_ID: "60058"
        PARTY_SIZE: "2"
      steps:
        - name: Checkout repo (so supporting files exist)
          uses: actions/checkout@v4
          with:
            fetch-depth: 1
        - name: Download binary
          run: |
              wget https://github.com/charles-fuss/resy-cli/releases/download/v1.2.0/resy-cli-lin -O resy-cli-lin
              chmod +x resy-cli-lin
        - name: Book reservation
          run: |
              #!/usr/bin/env bash
              set -euo pipefail
              
              echo "resy auth"
              ./resy-cli-lin setup
              echo "resy auth test"
              ./resy-cli-lin ping

              RES_DATE=$(date -d "+${RES_DAYS_AHEAD} days" '+%Y-%m-%d')
              TODAY_ET=$(TZ=America/New_York date +%F)
              TARGET_TS=$(TZ=America/New_York date -d "$TODAY_ET 09:00:00" +%s)
              NOW=$(date +%s)
              # sleep only if target is in the future
              if (( NOW < TARGET_TS )); then
                      echo "sleeping til it's time............"
                sleep $(( TARGET_TS - NOW ))
              fi


              # config
              BIN="$(pwd)/resy-cli-lin"               
              # times to attempt (one per invocation)
              TIMES=( "17:00:00" "17:15:00" "17:30:00" "17:45:00" "18:00:00" "18:15:00" "18:30:00" "18:45:00" \
                      "19:00:00" "19:15:00" "19:30:00" "19:45:00" "20:00:00" "20:15:00" "20:30:00" "20:45:00" \
                      "21:00:00" "21:15:00" "21:30:00" "21:45:00" "22:00:00" "22:15:00" "22:30:00" "22:45:00" \
                      "23:00:00" "23:15:00" "23:30:00" "23:45:00" "00:00:00" )

                for t in "${TIMES[@]}"; do
                  echo "Attempt: time=$t"
                  "$BIN" book --partySize "$PARTY_SIZE" --reservationDate "$RES_DATE" --reservationTimes "$t" --venueId "$VENUE_ID" || true
                done