name: Scheduled Booking Snipe

on:
  schedule:
    # Runs at 13:00 UTC (09:00 EDT when DST is active)
    - cron: '0 13 * * *'
    # Runs at 14:00 UTC (09:00 EST when standard time is active)
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  run-windows-binary-private:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Snipe monkey bar
        run: |
        - name: Run booking
        env:
          RES_DAYS_AHEAD: 20
          venueId: 60058
          partySize: 2
        run: |
            # PowerShell on windows-latest
            $ErrorActionPreference = "Stop"

            # compute reservation date
            $date = (Get-Date).AddDays($env:RES_DAYS_AHEAD).ToString('yyyy-MM-dd')
            Write-Host "Reservation date: $date"

            $times = @(
              "17:00:00","17:15:00","17:30:00","17:45:00",
              "18:00:00","18:15:00","18:30:00","18:45:00",
              "19:00:00","19:15:00","19:30:00","19:45:00",
              "20:00:00","20:15:00","20:30:00","20:45:00",
              "21:00:00","21:15:00","21:30:00","21:45:00",
              "22:00:00","22:15:00","22:30:00","22:45:00",
              "23:00:00","23:15:00","23:30:00","23:45:00",
              "00:00:00"
            )

            foreach ($t in $times) {
              Write-Host "Attempting booking at time: $t"
              .\resy-cli.exe book `
                --partySize=$env:PARTY_SIZE `
                --reservationDate=$date `
                --reservationTimes=$t `
                --venueId=$env:VENUE_ID `
                --reservationTypes=""
            }

            Write-Host "All attempts finished."